apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: "4.1.0"   # must be a supported version by your Strimzi operator
    nodePools:
      - name: kafka-pool-0
        replicas: 3
        template:
          pod:
            nodeSelector:
              agentpool: kafka
        storage:
          type: ephemeral
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
  zookeeper:
    replicas: 3
    template:
      pod:
        nodeSelector:
          agentpool: kafka
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
