spec:
  kafka:
    replicas: 3
    template:
      pod:
        nodeSelector:
          agentpool: kafka
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    template:
      pod:
        nodeSelector:
          agentpool: kafka
    storage:
      type: ephemeral
